### ISSUE TITLE
step() of LowpassFilterBlock does not seem to have any effect?

### ISSUE THREAD

**Issue by ksomml** [dlaidig/qmt#1]
https://github.com/dlaidig/qmt/blob/0fa8d32eb461e14d78e9ddbd569664ea59bcea19/qmt/blocks/utils.py#L39-L50

Tried using the step() method of the LowpassFilterBlock from the utils.py but did not have any success in seeing any filter results. My test code:

```
# Setup variables
frequency = 100
Ts = 1.0 / frequency
amplitude = 1 
sampling_rate = 500
duration = 1

# Generate example data
t = np.linspace(0, duration, int(sampling_rate * duration), endpoint=False)
sine_wave = amplitude * np.sin(2 * np.pi * frequency * t)

# Filter setup
f_cutoff = 5.0
filter = qmt.LowpassFilterBlock(Ts=Ts, fc=f_cutoff)
filtered = filter.step(sine_wave)

# Results
diff = sine_wave - filtered
```

diff is 0.0 for all samples throughout the data given was a sine wave with 100hz which is above f_cutoff of 5hz.

Am I doing something wrong? Why does the lowpass filter not seem to have any effect?

---

Also as a side question, I did not see any lowpass filter step in the joint axis estimation setup of the `fullbody_tracking_advanced_example.py` :

https://github.com/dlaidig/qmt/blob/0fa8d32eb461e14d78e9ddbd569664ea59bcea19/examples/full_body_tracking_advanced_example.py#L160-L177

Though according to `Non-restrictive Methods for Inertial Sensor Fusion in Human Motion Analysis, D. Laidig - Page 81`
> Low-pass filtering of the angular rates used for evaluating the rotation-based constraint with a cutoff frequency of fc = 5 Hz improves the accuracy and robustness of the anatomical calibration.

Was this left out on purpose for this example? Or does the lowpass Filter from VQF (`VQF: Highly Accurate IMU Orientation Estimation with Bias Estimation and Magnetic Disturbance Rejection, D. Laidig & T. Seel - Page 15`

> As a low-pass filter, we use a second-order Butterworth filter.

permanently modify the gyroscope data given from a .mat file so it is already filtered when doing the joint estimation step?

Regards
Kevin Sommler

**Comment by dlaidig** [comment]
> Am I doing something wrong? Why does the lowpass filter not seem to have any effect?

The `LowpassFilterBlock` is designed to be used for real-time demos in which one sample is processed at a time. To make it work with your example, you would need a loop and call the step function 500 times. The step function takes arrays as input in order to allow, e.g., for 3D vectors like gyr and acc to be filtered with one instance of this class. In your case, you filtered a 500-dimensional signal with only one sample, so the output is the same as the input. (But the documentation is not great, so I understand that it's not too clear...)

If you don't need to do real-time processing, you can just use `scipy.signal.butter` + `scipy.signal.lfilter_zi` + `scipy.signal.lfilter` to do the same filtering as `LowpassFilterBlock` (just way more efficiently).

> Also as a side question, I did not see any lowpass filter step in the joint axis estimation setup of the fullbody_tracking_advanced_example.py :

This it because the method qmt.jointAxisEstHingeOlsson that is used in the example script uses a different axis estimation algorithm based on this paper: https://www.mdpi.com/1424-8220/20/12/3534

In my 2D axis estimation code, I filter the gyroscope measurements (IIRC, with `scipy.signal.filtfilt` instead of `scipy.signal.lfilter`). Unfortunately, the code for this method is not integrated into `qmt`.

**Comment by ksomml** [comment]
> The LowpassFilterBlock is designed to be used for real-time demos in which one sample is processed at a time.

Ah, okay I did not know it was meant for real-time processing! Processing it 500 times did yield some results now.

> If you don't need to do real-time processing, you can just use scipy.signal.butter + scipy.signal.lfilter_zi + scipy.signal.lfilter to do the same filtering as LowpassFilterBlock (just way more efficiently).

Thats good to know, thanks!

> This it because the method qmt.jointAxisEstHingeOlsson that is used in the example script uses a different axis estimation algorithm based on this paper: https://www.mdpi.com/1424-8220/20/12/3534
> 
> In my 2D axis estimation code, I filter the gyroscope measurements (IIRC, with scipy.signal.filtfilt instead of scipy.signal.lfilter). Unfortunately, the code for this method is not integrated into qmt.

What code are you referring to if you say "in my 2D axis estimation code"? Your private code or code that is used in the `fullbody_tracking_advanced_example.py` which uses `qmt.jointAxisEstHingeOlsson`?

As far as I understand now, if I stay with using the integrated `qmt.jointAxisEstHingeOlsson` algorithm, I do not need to pre-filter my data for the Olsson axis estimation, as there have been no tests done to prove accuracy and robustness improvements by pre-filtering data?

Generally I want to stay with QMT for now instead of implementing (maybe more) sophisticated joint axis algorithms myself.

**Comment by dlaidig** [comment]
With "in my 2D axis estimation code", I was referring to the algorithm described in my PhD thesis (and in https://www.mdpi.com/1424-8220/22/24/9850) that you referred to in your initial post.

`qmt.jointAxisEstHingeOlsson` is designed for hinge (=1D) joints. If you want to use this algorithm in the original form, you shouldn't low-pass filter the data before passing it to the algorithm.

**Comment by ksomml** [comment]
Okay I understand now, then it was my mistake to have read that part of your PhD thesis about improving accuracy and robustness as general information for anatomical calibration processes (so it could be applied for the `qmt.jointAxisEstHingeOlsson` too) instead of information just for your algorithm. 

Thanks for taking the time and responding so quickly!
